version: "3.9"

services:
    django:
        build: .
        container_name: django
        command: >
          sh -c "python3 manage.py migrate &&
                 python3 manage.py runserver 0.0.0.0:8000 &&
                 python3 manage.py process_tasks"

        volumes:
          - .:/usr/src/app/
        ports:
          - "8000:8000"
        environment:
          - DEBUG=1
          - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1
        depends_on:
          - pgdb
          - redis
          - background_tasks
    background_tasks:
        build: .
        image: app
        container_name: background_tasks
        command: python manage.py process_tasks
        volumes:
          - .:/usr/src/app/
        depends_on:
          - pgdb
    pgdb:
        image: postgres
        container_name: pgdb
        ports:
          - "5432"
        environment:
          - POSTGRES_DB=Equb
          - POSTGRES_USER=equb
          - POSTGRES_PASSWORD=XY8g,C11
        volumes:
          - pgdata:/var/lib/postgresql/data
    redis:
      image: redis:alpine
      ports:
        - "6379:6379"
volumes:
  pgdata: