# Generated by Django 3.2.6 on 2021-08-29 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equbmembership',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
