# Generated by Django 5.0.4 on 2024-05-03 23:32

import django.db.models.deletion
import django.utils.timezone
import moneypool.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0003_auto_20220223_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equbinviterequest',
            name='equb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='moneypool.equb'),
        ),
        migrations.AlterField(
            model_name='equbinviterequest',
            name='receiver',
            field=models.ForeignKey(on_delete=models.SET(moneypool.models.deleted_user), related_name='received_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equbinviterequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equbjoinrequest',
            name='equb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='moneypool.equb'),
        ),
        migrations.AlterField(
            model_name='equbjoinrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=models.SET(moneypool.models.deleted_user), related_name='received_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equbjoinrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='receiver',
            field=models.ForeignKey(on_delete=models.SET(moneypool.models.deleted_user), related_name='received_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendrequest',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_%(class)ss', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friends', through='moneypool.Friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BalanceManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('last_managed', models.DateTimeField(blank=True, null=True)),
                ('finished_rounds', models.IntegerField(blank=True, default=0)),
                ('equb', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance_manager', to='moneypool.equb')),
                ('received', models.ManyToManyField(blank=True, related_name='received_equb_managers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('round', models.PositiveIntegerField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='moneypool.equb')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_bids', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-round', '-amount'],
            },
        ),
        migrations.CreateModel(
            name='HighestBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneypool.bid')),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bids', to='moneypool.equb')),
            ],
        ),
        migrations.CreateModel(
            name='OutBidNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
                ('round', models.IntegerField(default=0)),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moneypool.equb')),
                ('new_highest_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='moneypool.bid')),
                ('previous_highest_bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='moneypool.bid')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creation_date'],
                'abstract': False,
            },
        ),
    ]
