# Generated by Django 5.0.4 on 2024-06-23 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0007_paymentrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentConfirmation',
            new_name='PaymentConfirmationRequest',
        ),
        migrations.DeleteModel(
            name='PaymentRequest',
        ),
    ]
