# Generated by Django 5.0.4 on 2024-06-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0008_rename_paymentconfirmation_paymentconfirmationrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentconfirmationrequest',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=13),
        ),
    ]
