# Generated by Django 5.0.4 on 2024-06-23 23:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0009_paymentconfirmationrequest_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='EqubWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneypool.bid')),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wins', to='moneypool.equb')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
