# Generated by Django 5.0.4 on 2024-06-24 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0010_equbwinner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighestBid',
        ),
    ]
