# Generated by Django 5.0.4 on 2024-06-24 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0011_delete_highestbid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbidnotification',
            old_name='new_highest_bid',
            new_name='new_equb_winner',
        ),
        migrations.RenameField(
            model_name='outbidnotification',
            old_name='previous_highest_bid',
            new_name='previous_equb_winner',
        ),
    ]
