# Generated by Django 5.0.4 on 2024-06-24 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0012_rename_new_highest_bid_outbidnotification_new_equb_winner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outbidnotification',
            old_name='new_equb_winner',
            new_name='new_highest_bid',
        ),
        migrations.RenameField(
            model_name='outbidnotification',
            old_name='previous_equb_winner',
            new_name='previous_highest_bid',
        ),
        migrations.CreateModel(
            name='HighestBid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.PositiveIntegerField()),
                ('bid', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneypool.bid')),
                ('equb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='highest_bids', to='moneypool.equb')),
            ],
        ),
        migrations.DeleteModel(
            name='EqubWinner',
        ),
    ]
