# Generated by Django 5.0.4 on 2024-07-01 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0013_rename_new_equb_winner_outbidnotification_new_highest_bid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='highestbid',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
