# Generated by Django 5.0.4 on 2024-07-01 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0015_winner_balancemanager_winners'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancemanager',
            name='winners',
        ),
        migrations.AddField(
            model_name='balancemanager',
            name='winners',
            field=models.ManyToManyField(blank=True, null=True, related_name='winning_equb_managers', to='moneypool.winner'),
        ),
    ]
