# Generated by Django 5.0.4 on 2024-07-02 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0016_remove_balancemanager_winners_balancemanager_winners'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Winner',
            new_name='Win',
        ),
        migrations.RenameField(
            model_name='balancemanager',
            old_name='winners',
            new_name='wins',
        ),
    ]
