# Generated by Django 5.0.4 on 2024-07-04 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0018_alter_bid_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equb',
            name='current_round',
        ),
    ]
