# Generated by Django 5.0.4 on 2024-07-13 16:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0019_remove_equb_current_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='amount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0.001), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
