# Generated by Django 5.0.4 on 2024-07-14 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0020_alter_bid_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(choices=[('VE', 'Venmo'), ('PA', 'PayPal'), ('CA', 'CashApp')], max_length=2)),
                ('username', models.CharField(max_length=150)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selected_payment_methods', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='paymentconfirmationrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneypool.paymentmethod'),
        ),
        migrations.AddField(
            model_name='user',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, null=True, related_name='users', to='moneypool.paymentmethod'),
        ),
    ]
