# Generated by Django 5.0.4 on 2024-08-11 20:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0022_paymentmethod_unique_user_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='equb',
            name='is_in_payment_stage',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='balancemanager',
            name='wins',
            field=models.ManyToManyField(blank=True, related_name='winning_equb_managers', to='moneypool.win'),
        ),
        migrations.AlterField(
            model_name='user',
            name='friends',
            field=models.ManyToManyField(blank=True, through='moneypool.Friendship', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='users', to='moneypool.paymentmethod'),
        ),
    ]
