# Generated by Django 5.0.4 on 2024-08-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0023_equb_is_in_payment_stage_alter_balancemanager_wins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equbinviterequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='equbjoinrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paymentconfirmationrequest',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
    ]
