# Generated by Django 5.0.4 on 2024-08-12 01:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0024_equbinviterequest_is_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='score',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=3, validators=[django.core.validators.MinValueValidator(0.01), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
