# Generated by Django 5.0.4 on 2024-08-12 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0025_user_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentconfirmationrequest',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='paymentconfirmationrequest',
            name='service',
            field=models.CharField(choices=[('VE', 'Venmo'), ('PA', 'PayPal'), ('CA', 'CashApp')], default='VE', max_length=2),
        ),
    ]
