# Generated by Django 5.0.4 on 2024-08-12 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0026_remove_paymentconfirmationrequest_payment_method_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentconfirmationrequest',
            name='service',
        ),
        migrations.AddField(
            model_name='paymentconfirmationrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='moneypool.paymentmethod'),
        ),
    ]
