# Generated by Django 5.0.4 on 2024-08-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0027_remove_paymentconfirmationrequest_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancemanager',
            name='current_round_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
