# Generated by Django 5.0.4 on 2024-08-15 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0029_paymentconfirmationrequest_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='username',
            field=models.CharField(default='', max_length=150),
        ),
    ]
