# Generated by Django 5.0.4 on 2024-08-15 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0030_alter_paymentmethod_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='service',
            field=models.CharField(choices=[('Venmo', 'VE'), ('PayPal', 'PP'), ('CashApp', 'CA'), ('Cash', 'CASH'), ('Zelle', 'ZE')], max_length=150),
        ),
    ]
