# Generated by Django 5.0.4 on 2024-08-15 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0031_alter_paymentmethod_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmationrequest',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='moneypool.paymentmethod'),
        ),
    ]
