# Generated by Django 5.0.4 on 2024-08-15 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0032_alter_paymentconfirmationrequest_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentconfirmationrequest',
            name='equb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_confirmation_requests', to='moneypool.equb'),
        ),
        migrations.AlterField(
            model_name='paymentconfirmationrequest',
            name='payment_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='moneypool.paymentmethod'),
        ),
    ]
