# Generated by Django 5.0.4 on 2024-08-20 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0034_alter_paymentconfirmationrequest_equb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balancemanager',
            name='end_date',
        ),
        migrations.AddField(
            model_name='equb',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
