# Generated by Django 5.0.4 on 2024-08-20 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0035_remove_balancemanager_end_date_equb_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150),
        ),
    ]
