# Generated by Django 5.0.4 on 2024-08-28 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0038_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='win',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
