# Generated by Django 5.0.4 on 2024-09-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0039_win_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='service',
            field=models.CharField(choices=[('Venmo', 'Venmo'), ('PayPal', 'PayPal'), ('CashApp', 'CashApp'), ('Cash', 'Cash'), ('Zelle', 'Zelle'), ('Bank Transfer', 'Bank Transfer')], max_length=150),
        ),
    ]
