# Generated by Django 5.0.4 on 2024-09-07 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0040_alter_paymentmethod_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='username',
            new_name='detail',
        ),
    ]
