# Generated by Django 4.2.16 on 2024-10-05 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneypool', '0042_remove_paymentmethod_unique_user_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
